name: Deploy
on:
  push:
    branches:
      - master
      - dev
  schedule:
    - cron: '33 3 * * 1'
  workflow_dispatch:


jobs:
  build:
    name: Build, tag, and publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Get branch
        run: |
          echo "GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV
      - name: Set main docker image tag 
        run: |
          if [[ "$i{{ env.GIT_BRANCH }}" == "main" ]] || [[ "${{ env.GIT_BRANCH }}" == "master" ]]; then
            echo "MAIN_DOCKER_TAG=latest" >> $GITHUB_ENV
          else
            echo "MAIN_DOCKER_TAG=${{ env.GIT_BRANCH }}" >> $GITHUB_ENV
          fi
      - name: remove docker from repo name
        run: |
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | sed 's|^jee-r/docker-||g')" >> $GITHUB_ENV
      - name: crop SHA
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: print env
        run: echo $ENV
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master
      - name: Login into DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.MAIN_DOCKER_TAG }}
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.GIT_BRANCH }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.MAIN_DOCKER_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.GIT_BRANCH }} 
      - name: php_specs      
        run: |
          export SHA_IMAGE_NAME=ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}
          export BRANCH_IMAGE_NAME=ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ env.GIT_BRANCH }}
          mkdir -p artifacts
          echo "==== PHP VERSION ====" >> artifacts/php_specs.txt
          echo "$(docker run -tty --user 0:0  --entrypoint='' ${SHA_IMAGE_NAME} php -v)" >> artifacts/php_specs.txt
          echo "==== PHP MODULES ====" >> artifacts/php_specs.txt
          echo "$(docker run -tty --user 0:0  --entrypoint='' ${SHA_IMAGE_NAME} php -m)" >> artifacts/php_specs.txt
          echo "==== PHP INFO ====" >> artifacts/php_specs.txt
          echo "$(docker run -tty --user 0:0  --entrypoint='' ${SHA_IMAGE_NAME} php -i)" >> artifacts/php_specs.txt
          echo "==== ALPINE VERSION ====" >> artifacts/alpine_specs.txt
          echo "$(docker run -tty --user 0:0  --entrypoint='' ${SHA_IMAGE_NAME}  cat /etc/alpine-release)" >> artifacts/alpine_specs.txt
          echo "==== UNAME ====" >> artifacts/php_specs.txt
          echo "$(docker run -tty --user 0:0  --entrypoint='' ${SHA_IMAGE_NAME} uname --all)" >> artifacts/alpine_specs.txt
      - name: upload_artifact
        uses: actions/upload-artifact@v2
        with:
          name: specs_${{ env.GIT_BRANCH }}
          path: artifacts/*_specs.txt